spring:
  datasource:
    url: jdbc:mysql://localhost:13306/sfg_dev
    username: sfg_dev_user
    password: pa55w0rd
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true